### ISSUE TITLE
Torchfix as pre-commit hook

### ISSUE THREAD

**Issue by f-fuchs** [pytorch-labs/torchfix#63]
Hey,

I tried adding torchfix as a pre-commit hook with following config:

```
  - repo: local
    hooks:
      - id: torchfix
        name: torchfix
        entry: torchfix
        args: [--select=ALL, --fix]
        language: system
        types: [python]
        pass_filenames: true
```,

but I get following error when no python file is staged:
```
Traceback (most recent call last):
  File "/mnt/c/Users/fuchsfa/Desktop/Git/foundation-models/.venv/bin/torchfix", line 8, in <module>
    sys.exit(main())
  File "/mnt/c/Users/fuchsfa/Desktop/Git/foundation-models/.venv/lib/python3.10/site-packages/torchfix/__main__.py", line 110, in main
    result = codemod.parallel_exec_transform_with_prettyprint(
  File "/mnt/c/Users/fuchsfa/Desktop/Git/foundation-models/.venv/lib/python3.10/site-packages/libcst/codemod/_cli.py", line 575, in parallel_exec_transform_with_prettyprint
    raise Exception("Must have at least one job to process!")
Exception: Must have at least one job to process!
```
Is there an easy way to fix this?
